feat(comments): clarify include path syntax
openqasm/openqasm pull request #435
Opened 2022-12-24 04:52 UTC by sno2

The current definition of include paths may not allow for paths that are valid bit strings (e.g. `001`). This updates the specification and reference ANTLR parser to allow such cases as valid.

✅ I have added the tests to cover my changes.
✅ I have updated the documentation accordingly.
✅ I have read the CONTRIBUTING document.

Are you changing the specification? This PR needs to be approved by the TSC members.

Yes

Are you changing the grammar to adjust to the specification?

The specification is the source of truth and any grammar updates should also coincide with accepted specification updates in the same PR.

Yes

See #434 for summary, details, and comments.

2023-03-01 17:17 UTC, blakejohnson requested changes
I think you have correctly identified a bug in the ANTLR lexer. However, the spec already seems clear enough that `include` statements should accept any valid filename in the following string. @jakelishman wanted to suggest an alternative fix.

2023-03-01 18:54 UTC, jakelishman approved these changes
I've pushed up my changes - the principal difference is that we handle this within the lexer rather than the parser.  This makes it simpler for direct consumers of the ANTLR-generated parse tree to handle the output, which is shown here by the `openqasm3` package having been automatically upgraded to pass the new tests I wrote for it, without any change to the structure of either the ANTLR parser (only its lexer) or the `openqasm3` ANTLR parse-tree visitor.

I also fixed the same bug in the targets of `defcalgrammar`, since it was subject to the same thing.

2023-03-15 16:21 UTC, blakejohnson approved these changes

2023-03-15 16:22 UTC, blakejohnson commented
@jakelishman's version looks good to me.

2023-07-19 16:04 UTC, merged