Allow pragmas outside of global scope
openqasm/openqasm pull request #490
Opened 2023-11-09 19:31 UTC by braised-babbage

The OpenQASM spec includes a `pragma` directive

From [the spec](https://openqasm.com/language/directives.html#pragmas),

> Pragma directives start with pragma and continue to the end of line. The text after pragma is a single string, and parsing is left to the specific implementation. Implementations may optionally choose to support the older #pragma keyword as a custom extension. Pragmas should be processed as soon as they are encountered; if a pragma is not supported by a compiler pass it should be ignored and preserved intact for future passes. Pragmas should avoid stateful or positional interactions to avoid unexpected behaviors between included source files. **If the position is relevant to a pragma, an annotation should be used instead.**

The grammar places no restrictions on where pragmas may appear. However, the Python reference parser currently raises an exception if a pragma occurs outside of the global scope. I do not see the point of this restriction; if the meaning of a pragma is independent of its position, then one could simply allow them anywhere. 

This PR changes the parser to not treat pragmas outside of the global scope as an error. I don't think we need to change the spec in any way to support this.

To slightly motivate why I prefer the flexibility of a "pragma anywhere" approach, I will say that we often work with OpenQASM programs which are produced by combining various AST fragments. If any of these AST fragments includes a pragma, then their composition is not so simple. For example, we may wish to produce a defcal "on-the-fly", and as it stands the restriction on `pragma` placement requires that any pragmas associated by the defcal get percolated to the program toplevel by some mechanism. It would be much more convenient to allow defcals to carry pragma statements (one can imagine similar examples with other composite AST nodes, e.g. `if` and `else` blocks that get combined).

2023-12-20 14:26 UTC, blakejohnson approved these changes
Makes sense to me.

2023-12-20 14:34 UTC, jwoehr commented
If a pragma appears outside global scope, is its impact scoped locally or globally?

2023-12-20 14:39 UTC, jakelishman commented
Jack: if I recall correctly, that question is the reason the spec originally only allowed pragmas at the global scope. I'm fairly sure it was discussed, and there wasn't at the time a known use-case for local pragmas, so they were made global-only in order to avoid needing to answer that question.  I think it was approximately assumed that annotations could serve a more local purpose.

That said, I don't feel strongly, and my recollection is that the original reason for not allowing it was a lack of compelling use-case more than a technical reason.  Provided we do define how a local pragma is to be interpreted (even if just to say "a compiler is free to interpret this entirely however it likes"), I'm fine with it.

2023-12-20 15:06 UTC, jwoehr commented
> **Provided we do define how a local pragma is to be interpreted** (even if just to say "a compiler is free to interpret this entirely however it likes"), I'm fine with it.

Yes, that is the important point. Is a local pragma local in effect or global?

2023-12-21 05:31 UTC, braised-babbage commented
> > **Provided we do define how a local pragma is to be interpreted** (even if just to say "a compiler is free to interpret this entirely however it likes"), I'm fine with it.
> 
> Yes, that is the important point. Is a local pragma local in effect or global?

My view is that a pragma should be a kind of global signal to the compiler, regardless of whether it appeared in some particular lexical scope. If at some point we introduce a notion of separate compilation, I would be happy to consider pragmas applying to a particular compilation unit.

Probably the most ubiquitous notion of "pragma" is the one from C/C++ where the effect is global but position matters (i.e. pragmas apply as the file is processed top-to-bottom). Some of these are truly used as global signals, and others are just turned on and off for some portion of the program. In this respect I think the OpenQASM notion of annotation is a nice alternative mechanism to communicate information to the compiler with a clear & bounded extent. But if pragmas apply only to the scope block they are in, they would not offer much beyond what we can do with annotations.

2024-07-10 15:56 UTC, levbishop requested changes
I approve in principle after a reno and ideally a test

2024-08-07 19:53 UTC, braised-babbage commented
Based on the comments above and TSC discussion today (8/7/24), I am going to withdraw this PR, at least in its current form. My observation is that people interpreting the spec may come with various notions of what pragmas mean / are for, and we have relatively few concrete examples to pin discussions on. Because the effect of pragmas is independent of their position, there is a risk of confusion amongst human readers when pragmas appear some place other than at the top of a QASM file. There may still be room for spec clarifications, but that does not need to happen in this PR.

2024-08-07 19:53 UTC, closed without merging